# Generated by Django 5.0.2 on 2024-02-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_rename_code_planet_planet_alter_planet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='planet',
            field=models.CharField(),
        ),
    ]
